name: Build Ungoogled Chromium ARMhf

on:
  workflow_dispatch:   # cho phép bạn tự bấm nút chạy

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      # 1. Lấy code từ chính repo fork
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Cài dependencies build
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 git ninja-build clang \
              lld build-essential pkg-config

      # 3. Fetch source Chromium (dùng script có sẵn trong repo)
      - name: Fetch Chromium source
        run: |
          ./utils/downloads.py retrieve --platform linux_armhf

      # 4. Cấu hình build với GN
      - name: Configure build
        run: |
          gn gen out/Default --args="is_debug=false is_component_build=false \
            symbol_level=0 blink_symbol_level=0 enable_nacl=false \
            target_cpu=\"arm\" arm_version=7 treat_warnings_as_errors=false"

      # 5. Build với Ninja
      - name: Build Chromium
        run: |
          autoninja -C out/Default chrome

      # 6. Upload binary sau khi build
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: chromium-armhf
          path: out/Default/chrome
