name: Build Ungoogled Chromium ARMhf (minimal)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout fork
        uses: actions/checkout@v4

      - name: Install build deps
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 git ninja-build clang lld \
                                  build-essential pkg-config curl xz-utils zip

      # (Tùy chọn) Cache kho tải về để tăng tốc những lần build sau
      - name: Cache download_cache
        uses: actions/cache@v4
        with:
          path: build/download_cache
          key: dcache-${{ hashFiles('downloads.ini') }}

      # 1) Lấy Chromium source qua downloads.py (đúng cú pháp theo docs)
      - name: Retrieve and unpack Chromium source
        run: |
          mkdir -p build/download_cache
          python3 ./utils/downloads.py retrieve -c build/download_cache -i downloads.ini
          python3 ./utils/downloads.py unpack   -c build/download_cache -i downloads.ini -- build/src
        # Hướng dẫn: retrieve + unpack. :contentReference[oaicite:1]{index=1}

      # 2) Prune binaries không cần thiết
      - name: Prune binaries
        run: |
          python3 ./utils/prune_binaries.py build/src pruning.list
        # Theo bước "Prune binaries". :contentReference[oaicite:2]{index=2}

      # 3) Apply patches ungoogled
      - name: Apply patches
        run: |
          python3
