name: Build minimal Chromium for Armbian (ARMhf)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Free up space
        run: |
          dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -n | tail -n 100
          df -h
          echo "Removing large packages"
          sudo apt-get remove -y '^ghc-8.*'
          sudo apt-get remove -y '^dotnet-.*'
          sudo apt-get remove -y '^llvm-.*'
          sudo apt-get remove -y 'php.*'
          sudo apt-get remove -y azure-cli google-cloud-sdk hhvm google-chrome-stable firefox powershell mono-devel
          sudo apt-get autoremove -y
          sudo apt-get clean
          df -h
          echo "Removing large directories"
          rm -rf /usr/share/dotnet/
          df -h

      - name: Install depot_tools
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          echo "$GITHUB_WORKSPACE/depot_tools" >> $GITHUB_PATH

      - name: Install basic dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 git curl lsb-release

      - name: Get Chromium source
        run: |
          mkdir -p chromium
          cd chromium
          fetch --nohooks chromium

      - name: Install build dependencies
        run: |
          cd chromium/src
          sudo ./build/install-build-deps.sh --arm

      - name: Run hooks
        run: |
          cd chromium/src
          gclient runhooks

      - name: Install Rust toolchain
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env
          rustup target add armv7-unknown-linux-gnueabihf

      - name: Setup build directory
        run: |
          cd chromium/src
          gn gen out/Default --args='
            is_debug = false
            is_official_build = true
            target_os = "linux"
            target_cpu = "arm"
            arm_version = 7
            use_sysroot = true
            is_component_build = false
            symbol_level = 0
            blink_symbol_level = 0
            optimize_for_size = true
            treat_warnings_as_errors = false
            enable_nacl = false
            enable_webrtc = false
            enable_print_preview = false
            enable_swiftshader = false
            enable_vulkan = false
            enable_rust = true
            rust_sysroot = "$HOME/.rustup/toolchains/stable-x86_64-unknown-linux-gnu"
            rustc_version = "$(rustc --version | cut -d\" \" -f2)"
            rust_default_toolchain = "stable"
            rust_toolchain_target = "armv7-unknown-linux-gnueabihf"
          '

      - name: Build Chromium
        run: |
          cd chromium/src
          source $HOME/.cargo/env
          autoninja -C out/Default chrome

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: chromium-armhf
          path: chromium/src/out/Default
