name: Build Chromium ARMhf (minimal)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git python3 build-essential pkg-config ninja-build curl

      - name: Get depot_tools
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          echo "$GITHUB_WORKSPACE/depot_tools" >> $GITHUB_PATH

      - name: Fetch Chromium source
        run: |
          mkdir chromium && cd chromium
          fetch --nohooks chromium
          cd src
          # Ví dụ checkout một version ổn định (128 là stable mid-2024)
          git checkout tags/128.0.6613.137 -b build-armhf
          gclient sync

      - name: Configure build
        run: |
          cd chromium/src
          gn gen out/arm --args="`cat ../../args.gn`"

      - name: Build Chromium
        run: |
          cd chromium/src
          autoninja -C out/arm chrome

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: chromium-armhf
          path: chromium/src/out/arm/chrome
